[package]
name = "hello_rustyline"
version = "0.1.0"
edition = "2021"
default-run = "hello_rustyline"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "11.0.0"
reedline = "0.20.0"
