[package]
name = "hello_repl_completion"
version = "0.1.0"
edition = "2021"
default-run = "hello_repl_completion"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "11.0.0"
reedline = "=0.21.0"
nu-ansi-term = "=0.47.0"
